# config_search.yaml
# === 実験設定 ===
project_name: animalkingdom
experiment_name: triplet_vs_gan
output_root: ./train_result
datatype: wolf

# === モード設定 ===
train_mode: gated # mae / flow / gated
loss_type: triplet # supcon / cosine / triplet
adversarial: [gan, kl, dann] # True: GAN方式 / False: 通常正則化
flow_preprocessing: [normal, centered] # normal / centered
pooling: True

# === モデル設定 ===
fused_dim: 512
feature_dim: 256

# === ハイパーパラメータ探索 ===
triplet_margin: [0.05, 0.3]
temperature: 0.07 # 固定
lambda_adv: [0.01, 0.3]
lr_enc: [1e-5, 5e-4, log]
lr_disc: [1e-5, 5e-4, log]
batch_size: 32
disc_steps_per_batch: 1

# === 学習環境 ===
epochs: 100
num_workers: 4
pin_memory: true
device: cuda
seed: 42
use_cross_validation: true
cv_splits: 3
